### PR TITLE
Allow files to be selected for update in .apibuilder config files

### PR DESCRIPTION
**Pull request by gheine**
Second part of #21

### CODE REVIEW

**Comment by gheine** [comment]
@mchimirev @mbryzek now it should be fixed in .apibuilder files too (backward compatible)

**Comment by gheine** [comment]
@mbryzek thoughts?

**Comment by mbryzek** [comment]
FYI - have updated locally and running with out issue - can you merge?

**Comment by mbryzek** [comment]
released `0.1.10` with this change

**Pull request merged**
