### PR TITLE
.tracked_files should include relative, not absolute, paths

### PR DESCRIPTION
**Pull request by rlmartin**
This will prevent commit cruft when updating from different machines.

### CODE REVIEW

**Comment by rlmartin** [comment]
@mbryzek it seems safe to assume that `apibuilder` is always invoked from the same directory, i.e. the project's root directory? I believe this is the case, but wanted to confirm; otherwise this commit will need to be tweaked.

**Comment by mbryzek** [comment]
@rlmartin yeah - Perhaps a safer method is this:

https://github.com/apicollective/apibuilder-cli/pull/40

ie. pass in relative path directly

**Comment by rlmartin** [comment]
@mbryzek yeah, I thought about that but then you lose test coverage. The project config file must be in {root}/.apibuilder and there isn't anything in `app_config.rb` that allows for running the cli in any location other than the project root. Seems like a fairly safe assumption that it can be relative from the project root?

**Comment by mbryzek** [comment]
Either approach fine. Slight preference to keep pwd out of tracked files as may be less predictable over time 

Note For tests - can always add another apibuilder cli test that verified tracked files

**Comment by rlmartin** [comment]
@mbryzek I expanded this PR to also add the ability to invoke `apibuilder` from anywhere in the project (assuming it has been `git init`ed). The result is that I think it makes sense to pass the paojrect directory into the file_tracker - it also needs that dir to a) know where to write `.tracked_files` and b) prepend to the files to be deleted.

**Pull request merged**
